-- One owner, enforced by the database.
--
-- The first address to sign in claims the site (ADR 0012). Two gates in the
-- auth config decide that, and both of them READ before the insert writes:
-- two sign-ins against an empty `user` table can each see no owner, and D1
-- auto-commits every statement, so there is no transaction to hold between the
-- read and the write.
--
-- This index closes the race. The loser's insert fails instead of minting a
-- second owner. A partial index, so `viewer` rows are unconstrained.
--
-- Hand-written, not generated: `drizzle-kit` does not emit a partial index,
-- and `app/db/auth-schema.ts` is generated by the Better Auth CLI and never
-- hand-edited (ADR 0010).
--
-- Additive, like every migration here. It adds an index and touches no column.

CREATE UNIQUE INDEX IF NOT EXISTS one_owner ON "user" (role) WHERE role = 'owner';
